---
title: "Meeting Minutes"
format: html
author: 'Lewis Milun'
---


## Meeting on 9/3/2025

Arrived 2:15 PM
- Use playerid from pro-football-reference
- Make README.qmd
- Write data source and variable names/descriptions on README.qmd
- Find references
    + Put in apa.csl format
- Clean the data, then identify the problem to study


## Meeting on 9/10/2025

Arrived 2:14 PM
Others:
- QB trends since 2012
    + Maybe fantasy points (probably not)
- Use a series of variables
    + Make a plot for each one showing if there is correlation
    + GGplot in R 

- Looking at injury impact on team
- Switched to making a game predictor
- nflFastR
- Use old play-by-play data to predict outcomes of future games

Meeting minutes should include:
- What have we discussed
- What decision have we made
- What tasks do we have to do for next time


For me:
- Add description of how data was gotten
    + Put in a README how to get from rawData to final data
- Make plot for "exploratory analysis for motivation"
- Have data in form of [name, year, ypt]

Should I delete old data and code? (maybe just remove it)
- Y




## Meeting on 9/14/2025

Arrived 2:13 PM


- Clustered data regression
- Machine Learning
    - XGboost


## Meeting on 10/15/2025

Arrived 2:18 PM

- Collect Relavent literature

- Manuscript template
    - Write about 1 paragraph a day
    - Put problem formulation here so he can leave comments

- Use variable importance metrics
    - Shapely value
    - Search for more...
        - May be some for random forest
        - Look at his webpage publication #5 for an example

- For next week:
    - Put problem formulation in manuscript
    - Upload code to github



## Meeting on 10/29/2025

Arrived 2:25 PM

 - Use cross-validation score to assess models

 - Test/train split: ignore dependence for now
    - Just as a starting point, not ideal though
    - Data is clustered
    - test/train split at the subject level may help

- Neural networks can involve history
    - LSTM
    -Still do XGBoost for now

## Meeting on 11/5/2025

Arrived 2:22 PM

 - Changing models wouldn't really help much
 
 - Return yards being important is significant
    - "Dichotomize it"
    - On a separate note, check to see if relationship is positive or negative

- Should have enough to present next April at CSAS

- Start drafting manuscript

- Next semester 1 credit: "I'm offering something"